### ISSUE TITLE
Unable able to run python

### ISSUE THREAD

**Issue by jrowinski3d** [jborean93/pypsexec#26]
Hi there,

First of all, love this package!

I am running into an issue where I am trying to run **python.exe -c <command_here>** within powershell.exe but it keeps failing.

Also then tried to switch to running python directly without any luck and get Access Denied. I've tried elevated session, system accounts and I just feel like I am missing something small.

Any help would be appreciated or if you have done this in the past and could point me in the right direction.

```   
 try:
        c.create_service()
        result = c.run_executable("python.exe", run_elevated=True, username="xxx", password="xxx", arguments="-V")
        print(result)
    finally:
        c.cleanup()  # this is where the magic happens
        c.disconnect()
```

Thanks again for any help!

**Comment by jborean93** [comment]
Sorry for the delay, you should just be able to run it just as you have specified with the executable being `python.exe` and the arguments being `-c "command here"`. You say you are getting an access denied error, is that from running the process or just trying to get pypsexec to connect and setup the remote service. What is your Python command doing?

**Comment by jrowinski3d** [comment]
Hey @jborean93,

I moved away from trying to run `python.exe` and just using `powershell.exe`. The error was something along the lines "Cannot run executable on the system"

I would have to test it out again and see what the exact error was. Will do that and update you.

Right now I am facing STATUS_CANNOT_DELETE when trying remove_service() .
This happens right after "Creating open to PAExecfile with delete on close flags" in the logs.

As per Windows:

```

0xC0000121STATUS_CANNOT_DELETE | An attempt has been made to remove a file or directory that cannot be deleted.
-- | --
```

**Comment by jrowinski3d** [comment]
@jborean93 

Here is the error message for running python.exe

```
pypsexec.exceptions.PAExecException: Received exception from remote PAExec service: Failed to start "python.exe" -c "print('Hello')". The file cannot be accessed by the system. [Err=0x780, 1920]
```

**Comment by jborean93** [comment]
The error `ERROR_CANT_ACCESS_FILE 0x00000780` is unusual, usually a missing file is `ERROR_FILE_NOT_FOUND 0x00000002` or `ERROR_PATH_NOT_FOUND 0x00000003`. I've only been able to replicate this with the new AppExecLink with a target that does not exist.

This sounds suspiciously like the new AppExecLink reparse tags that Windows has started to include. In this particular case there is a file called `python.exe` in your profile which is in the PATH env var but because the package isn't installed hence the link not working. But because the file exists in the PATH Windows is trying to use that instead. To 100% verify that this is the problem I would run the following in PowerShell

```
$pythonPath = (Get-Command python.exe).Source
fsutil reparsepoint query $pythonPath
```

In my case I can see the following output

```
Reparse Tag Value : 0x8000001b
Tag value: Microsoft

Reparse Data Length: 0x000001d0
Reparse Data:
0000:  03 00 00 00 4d 00 69 00  63 00 72 00 6f 00 73 00  ....M.i.c.r.o.s.
0010:  6f 00 66 00 74 00 2e 00  44 00 65 00 73 00 6b 00  o.f.t...D.e.s.k.
0030:  73 00 74 00 61 00 6c 00  6c 00 65 00 72 00 5f 00  s.t.a.l.l.e.r._.
0040:  38 00 77 00 65 00 6b 00  79 00 62 00 33 00 64 00  8.w.e.k.y.b.3.d.
0050:  38 00 62 00 62 00 77 00  65 00 00 00 4d 00 69 00  8.b.b.w.e...M.i.
0060:  63 00 72 00 6f 00 73 00  6f 00 66 00 74 00 2e 00  c.r.o.s.o.f.t...
0070:  44 00 65 00 73 00 6b 00  74 00 6f 00 70 00 41 00  D.e.s.k.t.o.p.A.
0080:  70 00 70 00 49 00 6e 00  73 00 74 00 61 00 6c 00  p.p.I.n.s.t.a.l.
0090:  6c 00 65 00 72 00 5f 00  38 00 77 00 65 00 6b 00  l.e.r._.8.w.e.k.
00a0:  79 00 62 00 33 00 64 00  38 00 62 00 62 00 77 00  y.b.3.d.8.b.b.w.
00b0:  65 00 21 00 50 00 79 00  74 00 68 00 6f 00 6e 00  e.!.P.y.t.h.o.n.
00c0:  52 00 65 00 64 00 69 00  72 00 65 00 63 00 74 00  R.e.d.i.r.e.c.t.
00d0:  6f 00 72 00 00 00 43 00  3a 00 5c 00 50 00 72 00  o.r...C.:.\.P.r.
00e0:  6f 00 67 00 72 00 61 00  6d 00 20 00 46 00 69 00  o.g.r.a.m. .F.i.
00f0:  6c 00 65 00 73 00 5c 00  57 00 69 00 6e 00 64 00  l.e.s.\.W.i.n.d.
0100:  6f 00 77 00 73 00 41 00  70 00 70 00 73 00 5c 00  o.w.s.A.p.p.s.\.
0110:  4d 00 69 00 63 00 72 00  6f 00 73 00 6f 00 66 00  M.i.c.r.o.s.o.f.
0120:  74 00 2e 00 44 00 65 00  73 00 6b 00 74 00 6f 00  t...D.e.s.k.t.o.
0130:  70 00 41 00 70 00 70 00  49 00 6e 00 73 00 74 00  p.A.p.p.I.n.s.t.
0140:  61 00 6c 00 6c 00 65 00  72 00 5f 00 31 00 2e 00  a.l.l.e.r._.1...
0150:  30 00 2e 00 33 00 32 00  39 00 31 00 32 00 2e 00  0...3.2.9.1.2...
0160:  30 00 5f 00 78 00 36 00  34 00 5f 00 5f 00 38 00  0._.x.6.4._._.8.
0170:  77 00 65 00 6b 00 79 00  62 00 33 00 64 00 38 00  w.e.k.y.b.3.d.8.
0180:  62 00 62 00 77 00 65 00  5c 00 41 00 70 00 70 00  b.b.w.e.\.A.p.p.
0190:  49 00 6e 00 73 00 74 00  61 00 6c 00 6c 00 65 00  I.n.s.t.a.l.l.e.
01a0:  72 00 50 00 79 00 74 00  68 00 6f 00 6e 00 52 00  r.P.y.t.h.o.n.R.
01b0:  65 00 64 00 69 00 72 00  65 00 63 00 74 00 6f 00  e.d.i.r.e.c.t.o.
01c0:  72 00 2e 00 65 00 78 00  65 00 00 00 30 00 00 00  r...e.x.e...0...
```

The key value out of this is the reparse tag `0x8000001b` which is an [IO_REPARSE_TAG_APPEXECLINK](https://github.com/wine-mirror/wine/blob/c6b852e3c37247a01547d8ab9d1630684f9c5aaa/include/winnt.h#L2732) and it is pointing to an executable in `C:\Program Files\WindowsApps` which opens up a link to the Windows store. I don't agree with MS on this but your options are

* Remove the file at `$pythonPath` so it isn't found in the PATH
* Put your actual python installation at a higher precedence in the PATH env var
* Remove the WindowsApps dir from the PATH env var (I wouldn't do this)

Some background on this can be found in [this great block post about AppExecLinks](https://www.tiraniddo.dev/2019/09/).

> Right now I am facing STATUS_CANNOT_DELETE when trying remove_service() .

This is an unfortunate side effect of PAExec service which this library uses and is currently tracked with https://github.com/jborean93/pypsexec/issues/16. I'm in the middle of creating my own service implementation which should fix this but for now it will continue to be a problem if PAExec fails to start any process.

**Comment by jborean93** [comment]
Closing as per the above.
