### ISSUE TITLE
interactive mode only work properly with use_system_account=True

### ISSUE THREAD

**Issue by cfrelet** [jborean93/pypsexec#40]
Hi,

If I don't add `use_system_account=True` in `run_executable`, the window that open on the remote pc will be opened but can't be used to interact properly. It's blured.

```
from pypsexec.client import Client
c = Client("PC_NAME", username="cib\\user", password="pwd")
c.connect()
try:
    c.create_service()
    stdout, stderr, rc = c.run_executable("cmd.exe",
                                          arguments="/k echo Hello World", interactive=True, interactive_session=2)
except Exception as e:
    print(f'error: {e}')
finally:
    c.remove_service()
    c.disconnect()
```
![image](https://user-images.githubusercontent.com/45927310/102466915-9b4b4d00-408a-11eb-9cbc-8a2fe379b2c2.png)

The only way to make it work is to use use_system_account=True

```
    stdout, stderr, rc = c.run_executable("cmd.exe",
                                          arguments="/k echo Hello World", interactive=True, interactive_session=2,use_system_account=True)
```
But if I do so, the task is running with SYSTEM account and it's not what I need. Any advice?

![image](https://user-images.githubusercontent.com/45927310/102467140-e6fdf680-408a-11eb-9c01-785fe1b60ecb.png)

**Comment by jborean93** [comment]
Unfortunately this is a limitation of [PAExec](https://github.com/poweradminllc/PAExec) which is the binary we use for the Windows service that pypsexec starts up. I've had a long running ambition to replace PAExec in this library with my own library https://github.com/jborean93/pypsexec_service but I only got to the initial stages. I know this is possible to achieve as it was something I tested myself but I'm a long way away from having that ready as a replacement.

The only thing you can really do is submit a bug on the PAExec github page and hope someone looks into it but I'm not sure how proactive the maintainers are of it.

**Comment by jborean93** [comment]
Just as an FYI the "fix" that I found for this is to ensure we add the Logon Session SID of the primary access token in the session specified https://github.com/jborean93/pypsexec_service/blob/68075ddf8516bbb23f0a5054456a8122911ba98a/src/main.cpp#L84-L94. The reason this works is because the new process that is spawned has that logon session group which is allowed to access the interactive desktop just like a normal user would. Current PAExec does not do this and SYSTEM works because it has enough rights to do this without requiring that extra group.
