### ISSUE TITLE
Custom PipeName

### ISSUE THREAD

**Issue by unkn0wnsyst3m** [jborean93/pypsexec#52]

**Comment by unkn0wnsyst3m** [comment]
Update: I may have figured it out, looks like there is a hard coded pipe name in the paexec binary and pypsexec looks for that pipename

**Comment by jborean93** [comment]
It's been a while since I last played with the pipe named but AFAIK the first pipe is based on the name of the executable that is being run. For example pypsexec will copy the PAExec binary to `C:\Windows\PAExec-tmp-id.exe` and thus the pipe will be called `PAExec-tmp-id`. From there the pypsexec client will send across the process details to run and it creates 3 more pipes with the same prefix but now the `Out`, `In`, and `Err` suffixes. So if you wanted to use a different prefix for the pipe you need to modify the code that copies the binary to the remote host to use a different prefix.
